ALTER TABLE workspaces
ADD COLUMN IF NOT EXISTS auto_report_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS auto_report_period VARCHAR(20) DEFAULT 'weekly',
ADD COLUMN IF NOT EXISTS auto_report_time VARCHAR(10) DEFAULT '08:00',
ADD COLUMN IF NOT EXISTS last_auto_report_sent TIMESTAMP;
